### ISSUE TITLE
subaccount wad337

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#1]
subaccount "wad337" is entered in the database 2x, one needs to be deleted (and any references to it need to be assoicated with the other subaccount)
![image](https://cloud.githubusercontent.com/assets/17777303/13714697/4e1f87de-e79e-11e5-84d4-1aacbbad4818.png)

![image](https://cloud.githubusercontent.com/assets/17777303/13714734/6b378f4c-e79e-11e5-9df3-241fd3864ac7.png)

**Comment by baansconsulting** [comment]
Fixed

**Comment by TomGang** [comment]
I still see 2x this subaccount
![image](https://cloud.githubusercontent.com/assets/17777303/13782804/0980ef42-ea9f-11e5-9a34-025bdda5a939.png)

**Comment by baansconsulting** [comment]
So we are saying to delete duplicate sub-accounts?

**Comment by TomGang** [comment]
yes, there shouldn't ever be duplicate subaccounts... if any records are assigned to the 2nd instance of the duplicate subaccount, they should be updated to reference the surviving subaccount (so no broken links)

**Comment by baansconsulting** [comment]
changes done on server

**Comment by TomGang** [comment]
looks good. thanks
